### ISSUE TITLE
List of suggested image is not DISTRO aware

### ISSUE THREAD

**Issue by koenkooi** [96boards/oe-rpb-manifest#23]
When selecting a DISTRO the suggested image list includes a wayland image.

**Comment by ndechesne** [comment]
is that really an issue? i think i had said on another issue (iirc , trevor had a patch for that), that it would make the setup script too 'clumsy' if we have to list 'images' for each distro. especially because we have the DISTRO_FEATURES_REQUIRED fields in the image recipe, so trying to build an image with a 'wrong' distro should give an obvious error message.

well my main concern is to make sure we don't add to much complexity in setup-env script..
