### ISSUE TITLE
go-fsnotify GitHub link is broken

### ISSUE THREAD

**Issue by behlingc** [96boards/oe-rpb-manifest#91]
github link has changed. 'meta-virtualization' has to be set to at least

http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/recipes-devtools/go/go-fsnotify_git.bb?id=e63819669747585baa0284528ac76bdd34fc9e78

Error log:
`ERROR: go-fsnotify-1.2.11+git836bfd95fecc0f1511dd66bdbf2b5b61ab8b00b6-r0 do_fetch: Fetcher failure: Unable to find revision 836bfd95fecc0f1511dd66bdbf2b5b61ab8b00b6 in branch master even from upstream
ERROR: go-fsnotify-1.2.11+git836bfd95fecc0f1511dd66bdbf2b5b61ab8b00b6-r0 do_fetch: Fetcher failure for URL: 'git://github.com/go-fsnotify/fsnotify.git'. Unable to fetch URL from any source.
ERROR: go-fsnotify-1.2.11+git836bfd95fecc0f1511dd66bdbf2b5b61ab8b00b6-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/behlingc/dragonboard/build-rpb/tmp-rpb-glibc/work/aarch64-linaro-linux/go-fsnotify/1.2.11+git836bfd95fecc0f1511dd66bdbf2b5b61ab8b00b6-r0/temp/log.do_fetch.9633
ERROR: Task (/home/behlingc/dragonboard/build-rpb/conf/../../layers/meta-virtualization/recipes-devtools/go/go-fsnotify_git.bb:do_fetch) failed with exit code '1'
`

**Comment by ndechesne** [comment]
hey. you are correct. however why do you report this as an issue here? From what I am seeing this bug was fixed in meta-virtualization, so you should not be impacted, once you update your OE RPB workspace (e.g. repo sync). 

If I am missing anything, please let me know, and provide more information about your config.
